### ISSUE TITLE
Deprecation issue when updating julia

### ISSUE THREAD

**Issue by pstaabp** [staticfloat/homebrew-juliadeps#100]
I just did an update on julia-0.5 and got the following error:

```
Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/Users/XXXXX/.julia/v0.5/Homebrew/deps/usr/Library/Taps/staticfloat/homebrew-juliadeps/glpk452.rb:12:in `block in <class:Glpk452>'
Please report this to the staticfloat/juliadeps tap!
```

**Comment by ararslan** [comment]
Looks like this was fixed in https://github.com/staticfloat/homebrew-juliadeps/commit/645aa89f56967314acadc09ed938d54ab301dc90. The warning should be gone if you do `brew update`

**Comment by staticfloat** [comment]
Yep, this should be fixed now.  Please comment here again if it's not.
