### ISSUE TITLE
No checksums?

### ISSUE THREAD

**Issue by tdsmith** [staticfloat/homebrew-juliadeps#113]
Hi @staticfloat,

Installing some Julia packages I noticed:

```
==> Installing staticfloat/juliadeps/zeromq32
==> Downloading http://download.zeromq.org/zeromq-3.2.5.tar.gz
==> Downloading from https://ia800403.us.archive.org/10/items/zeromq_3.2.5/zeromq-3.2.5.tar.gz
######################################################################## 100.0%
Warning: Cannot verify integrity of zeromq32-3.2.5.tar.gz
A checksum was not provided for this resource
For your reference the SHA256 is: 09653e56a466683edb2f87ee025c4de55b8740df69481b9d7da98748f0c92124
```

I was surprised that Julia fetched a tarball over HTTP without integrity control; can I convince you to use the Homebrew checksum feature? :)

**Comment by ararslan** [comment]
Out of curiosity what version of MacOS are you running?

**Comment by tdsmith** [comment]
Sierra, which is why the bottle isn't being fetched, but it seems like checksums should be present for both bottles and the source tarballs.

**Comment by ararslan** [comment]
Right. We have a zeromq bottle for Sierra but it hasn't been put into production yet. That should happen fairly soon, I think. I can also add the checksum for the source tarball.

**Comment by ararslan** [comment]
Okay, I've added the source SHA for zeromq. It will go live at the same time as the Sierra bottle.

**Comment by tdsmith** [comment]
Thanks!
