### ISSUE TITLE
imagemagick 7

### ISSUE THREAD

**Issue by bjarthur** [staticfloat/homebrew-juliadeps#114]
@staticfloat 

homebrew has upgraded to 7 and dropped support for 6.  this breaks ImageMagick.jl.

i see that we have bottles for 6.8.9 and 6.9.2 at `https://juliabottles.s3.amazonaws.com`.  i gather we used to have an `imagemagick.rb` too.  would it make sense to re-instate it until ImageMagick.jl is upgraded to 7?

happy to help in anyway i can.

see discussion [here](https://github.com/JuliaIO/ImageMagick.jl/issues/57).

**Comment by staticfloat** [comment]
Thanks for this report @bjarthur, I agree, we should host our own bottles to provide the best user experience and to not drive up `crazymykl`'s hosting costs too much.  ;)

I've built bottles for this formula, so go ahead and try a `Homebrew.update()` and then switch over to `staticfloat/juliadeps/imagemagick@6` and see if this solves your problems.

**Comment by ilovezfs** [comment]
@bjarthur @staticfloat Just a heads up that we've now merged ImageMagick 6 as "imagemagick@6"

**Comment by bjarthur** [comment]
@staticfloat is there any reason not to revert back to homebrew's bottle?  i appreciate your effort getting our own bottle online.  but might as well have them bear the hosting costs, no?

**Comment by staticfloat** [comment]
Yes, absolutely.  If we can use Homebrew's bottles, then we should always do so.

**Comment by ilovezfs** [comment]
>but might as well have them bear the hosting costs

Just for the record, those costs are covered gratis by Bintray for us.

**Comment by staticfloat** [comment]
To be clear, it's not quite the hosting costs that I'm looking to dodge here, we actually cache a LOT of stuff on AWS (not Homebrew bottles in this case, but pretty much every other binary dependency!) it's more that having the Homebrew team provide the bottles takes a lot of work off of my shoulders regarding maintaining the binaries and ensuring they work across a range of OSX versions, etc...

**Comment by ilovezfs** [comment]
Yup makes sense! Just wanted to give credit where credit is due.

**Comment by bjarthur** [comment]
https://github.com/JuliaIO/ImageMagick.jl/pull/60
