### ISSUE TITLE
Bump SCS to 1.2.6

### ISSUE THREAD

**Issue by mlubin** [staticfloat/homebrew-juliadeps#115]
Pending https://github.com/JuliaLang/METADATA.jl/pull/8177

Thanks!

@staticfloat @kalmarek @joehuchette

**Comment by mlubin** [comment]
Oh we have a slight issue. The SCS.jl release compatible with julia 0.4 won't support this version of SCS. What do we do here?

@tkelman

**Comment by tkelman** [comment]
versioned formula name?

**Comment by staticfloat** [comment]
I've create the `scs118` formula.  You should release an `SCS v0.2.8` based off of your `Julia 0.4` codebase that uses that formula, and we'll continue to use `scs` as the latest version.
