### ISSUE TITLE
MinGW-w64 cross-compilers

### ISSUE THREAD

**Issue by tkelman** [staticfloat/homebrew-juliadeps#27]
Upstream homebrew doesn't have these, but there are some taps floating around that might work: https://github.com/cosmo0920/homebrew-mingw_w64 (would likely need a bit of tweaking, enabling gfortran and using the exception handling mode we want, etc)

If we tried bottling these on the buildbots to make them conveniently available, would anyone use them to try cross-compiling things? Binaries for packages, Julia herself, whatever. Or is it easier to install packer/vagrant and use a native Windows VM? Not many people seem to go to the trouble of doing the latter.

**Comment by staticfloat** [comment]
I think cross-compiling is a black art that not many attempt, and I'm not sure this is worth the effort.  (I say, six months after you post this.... sorry!)

**Comment by tkelman** [comment]
I disagree, but I also don't think this has to be done here. For now it's easy enough to fire up a Vagrant VM from OS X that I'll recommend people do that.
