### ISSUE TITLE
Ipopt's pkg-config files need some patching to deal with libgfortran location

### ISSUE THREAD

**Issue by tkelman** [staticfloat/homebrew-juliadeps#29]
I'm trying to make a package that links against the bottled binaries of Ipopt (and Cbc, but I think that bit's working okay). The upstream code is set up to just use pkg-config to get the right linker flags, so I'm setting `PKG_CONFIG_PATH` to `joinpath(Homebrew.prefix(), "lib", "pkgconfig")` on OSX. This ends up failing to link with the following:

```
clang++ -dynamiclib -single_module  -o .libs/libbonmin.4.7.4.dylib .libs/libbonmin.4.7.4.dylib-master.o  -L/Users/travis/.julia/v0.3/Homebrew/deps/usr/Cellar/cbc/2.8.12/lib -L/Users/travis/.julia/v0.3/Homebrew/deps/usr/Cellar/ipopt/3.11.8_1/lib -L/Users/travis/.julia/v0.3/Homebrew/deps/usr/Cellar/gcc/4.9.2_1/lib/gcc/4.9/gcc/x86_64-apple-darwin13.4.0/4.9.2 -L/Users/travis/.julia/v0.3/Homebrew/deps/usr/Cellar/gcc/4.9.2_1/lib/gcc/4.9/gcc/x86_64-apple-darwin13.4.0/4.9.2/../../.. -lCbcSolver -lCbc -lpthread -lCgl -lOsiClp -lClp -lOsi -lCoinUtils -lbz2 -lz -lipopt /Users/travis/.julia/v0.3/Homebrew/deps/usr/Cellar/ipopt/3.11.8_1/lib/libcoinlapack.a -ldl -lcoinmumps /Users/travis/.julia/v0.3/Homebrew/deps/usr/Cellar/ipopt/3.11.8_1/lib/libcoinblas.a -lgfortran -lSystem -lquadmath -lm  -install_name  /Users/travis/.julia/v0.3/OptimizationServices/deps/usr/lib/libbonmin.4.dylib -compatibility_version 12 -current_version 12.4
ld: warning: directory not found for option '-L/Users/travis/.julia/v0.3/Homebrew/deps/usr/Cellar/gcc/4.9.2_1/lib/gcc/4.9/gcc/x86_64-apple-darwin13.4.0/4.9.2'
ld: warning: directory not found for option '-L/Users/travis/.julia/v0.3/Homebrew/deps/usr/Cellar/gcc/4.9.2_1/lib/gcc/4.9/gcc/x86_64-apple-darwin13.4.0/4.9.2/../../..'
ld: library not found for -lgfortran
```

I guess the bottle builder was using a gfortran installed at the private Homebrew.jl location instead of the usual system path? Also there's no unversioned symlink to `libgfortran.dylib` installed by these bottles, AFAICT. I guess the gcc formula is in charge of that symlink in the default prefix/lib, but maybe we could add a private symlink in your libgfortran formula's Cellar path? Then by replacing Cellar/gcc/<...> with Cellar/libgfortran/<...> in ipopt.pc maybe this could be made to work?

**Comment by tkelman** [comment]
Here's what the pkg-config file looks like from a current install of the ipopt bottle: https://gist.github.com/sbromberger/4c89afe978550c8fd28b

**Comment by mlubin** [comment]
Is this for OS?

**Comment by tkelman** [comment]
yes - wip at https://github.com/tkelman/OptimizationServices.jl, nothing there yet except bindeps

we could just go straight to bottling it?

**Comment by mlubin** [comment]
Ah, bonmin

**Comment by tkelman** [comment]
I'm also entirely separately having the same BinDeps problem as https://groups.google.com/forum/#!topic/julia-users/ckxs2pC2Fw0 with Ipopt on Linux, trying to set rpath but failing to gist config.log from Travis

**Comment by mlubin** [comment]
I don't think it would be particularly terrible in the first pass if you just let OS build its own version of Ipopt and Cbc. That's not tidy enough for WinRPM, but otherwise I won't be complaining about the extra 10MB used by the duplicate binaries.

**Comment by tkelman** [comment]
Yeah, that will probably be easier for now. Still would be nice to save compilation time on OSX Travis though. The right way to do that is probably bottle it all and let Homebrew manage the interdependencies once the source build works.

**Comment by tkelman** [comment]
Linux issue tracked down to https://github.com/JuliaLang/julia/pull/8442#issuecomment-69449027 - this affects Ipopt.jl as well, for anyone who uses the generic Linux binaries instead of a source compile or a version from their package manager, because the bundled copy of libgfortran in the generic Linux binaries is incompatible with the system copy.

**Comment by staticfloat** [comment]
Ah, I see.  The pkg-config file is out of sync with reality since we're not relying on the full `gcc` bottle, but instead have my own little `libgfortran` dependency.  If you modify `ipopt.pc` to look [like this instead](https://gist.github.com/staticfloat/a0b360cf59f12c973064), does your software build properly?  I can do this automatically inside of the `ipopt` formula, but let's make sure that works first.

**Comment by tkelman** [comment]
Any idea why I would get permission errors from trying to do
```
download("https://gist.githubusercontent.com/staticfloat/a0b360cf59f12c973064/raw/93aa7f050b02dad31a391d4ec259d186c6b2c607/ipopt.pc",
        joinpath(Homebrew.prefix(), "lib", "pkgconfig", "ipopt.pc"))
```
?

**Comment by staticfloat** [comment]
`ipopt.pc` might not be writable by default?

**Comment by tkelman** [comment]
lets see if chmod helps

**Comment by tkelman** [comment]
rm worked, but couldn't find the Ipopt headers with that .pc file - I think the prefix needs to be from Homebrew.jl

**Comment by staticfloat** [comment]
Yes.  Homebrew should be automatically relocating those `.pc` files though,
so now that I've created a new version of the bottle with proper "-L"
flags, this should work I think.  Go ahead and `Homebrew.update()`, remove
`ipopt` and add it again and let's see what happens.

**Comment by tkelman** [comment]
Okay, still couldn't link to `-lgfortran`, https://travis-ci.org/tkelman/OptimizationServices.jl/jobs/46539474. How does linking to versioned dylibs work on OSX? Does your libgfortran formula need to make a private unversioned symlink?
```
clang++ -dynamiclib -single_module  -o .libs/libbonmin.4.7.4.dylib .libs/libbonmin.4.7.4.dylib-master.o  -L/Users/travis/.julia/v0.4/Homebrew/deps/usr/Cellar/cbc/2.8.12/lib -L/Users/travis/.julia/v0.4/Homebrew/deps/usr/Cellar/ipopt/3.11.8_1/lib -L/Users/travis/.julia/v0.4/Homebrew/deps/usr/Cellar/libgfortran/4.9.2_1/lib/ -L/Users/travis/.julia/v0.4/Homebrew/deps/usr/Cellar/gcc/4.9.2_1/lib/gcc/4.9/gcc/x86_64-apple-darwin13.4.0/4.9.2 -L/Users/travis/.julia/v0.4/Homebrew/deps/usr/Cellar/gcc/4.9.2_1/lib/gcc/4.9/gcc/x86_64-apple-darwin13.4.0/4.9.2/../../.. -lCbcSolver -lCbc -lpthread -lCgl -lOsiClp -lClp -lOsi -lCoinUtils -lbz2 -lz -lipopt /Users/travis/.julia/v0.4/Homebrew/deps/usr/Cellar/ipopt/3.11.8_1/lib/libcoinlapack.a -ldl -lcoinmumps /Users/travis/.julia/v0.4/Homebrew/deps/usr/Cellar/ipopt/3.11.8_1/lib/libcoinblas.a -lgfortran -lSystem -lquadmath -lm  -install_name  /Users/travis/.julia/v0.4/OptimizationServices/deps/usr/lib/libbonmin.4.dylib -compatibility_version 12 -current_version 12.4
ld: warning: directory not found for option '-L/Users/travis/.julia/v0.4/Homebrew/deps/usr/Cellar/gcc/4.9.2_1/lib/gcc/4.9/gcc/x86_64-apple-darwin13.4.0/4.9.2'
ld: warning: directory not found for option '-L/Users/travis/.julia/v0.4/Homebrew/deps/usr/Cellar/gcc/4.9.2_1/lib/gcc/4.9/gcc/x86_64-apple-darwin13.4.0/4.9.2/../../..'
ld: library not found for -lgfortran
```

**Comment by tkelman** [comment]
man you're fast - that last comment / error was with my own tweaked pc, building now with your new bottle

**Comment by tkelman** [comment]
with the updated bottle (https://travis-ci.org/tkelman/OptimizationServices.jl/jobs/46539984) at least there's no "directory not found" warnings, so that's some progress
```
clang++ -dynamiclib -single_module  -o .libs/libbonmin.4.7.4.dylib .libs/libbonmin.4.7.4.dylib-master.o  -L/Users/travis/.julia/v0.4/Homebrew/deps/usr/Cellar/cbc/2.8.12/lib -L/Users/travis/.julia/v0.4/Homebrew/deps/usr/Cellar/ipopt/3.11.8_1/lib -L/Users/travis/.julia/v0.4/Homebrew/deps/usr/opt/libgfortran/lib -lCbcSolver -lCbc -lpthread -lCgl -lOsiClp -lClp -lOsi -lCoinUtils -lbz2 -lz -lipopt /Users/travis/.julia/v0.4/Homebrew/deps/usr/Cellar/ipopt/3.11.8_1/lib/libcoinlapack.a -ldl -lcoinmumps /Users/travis/.julia/v0.4/Homebrew/deps/usr/Cellar/ipopt/3.11.8_1/lib/libcoinblas.a -lgfortran -lSystem -lquadmath -lm  -install_name  /Users/travis/.julia/v0.4/OptimizationServices/deps/usr/lib/libbonmin.4.dylib -compatibility_version 12 -current_version 12.4
ld: library not found for -lgfortran
```

**Comment by staticfloat** [comment]
Can you `ls -la /Users/travis/.julia/v0.4/Homebrew/deps/usr/opt/libgfortran/lib` to see if anything's actually getting installed there?

**Comment by staticfloat** [comment]
It's doing what I wanted it to do, but it seems to not be working.  :P

**Comment by tkelman** [comment]
give https://travis-ci.org/tkelman/OptimizationServices.jl/jobs/46540766 a few minutes

**Comment by tkelman** [comment]
```
total 4120
drwxr-xr-x  5 travis  staff      170 Nov 23 11:37 .
drwxr-xr-x  5 travis  staff      170 Jan 10 10:56 ..
-r--r--r--  1 travis  staff   272860 Jan 10 10:56 libgcc_s.1.dylib
-r--r--r--  1 travis  staff  1551568 Jan 10 10:56 libgfortran.3.dylib
-r--r--r--  1 travis  staff   279328 Jan 10 10:56 libquadmath.0.dylib
```

**Comment by staticfloat** [comment]
Welp, I'm guessing that I need to make `libgfortran.dylib -> libgfortran.3.dylib` symlinks.  Gimme a minute.

**Comment by staticfloat** [comment]
okay.  shoot.

**Comment by tkelman** [comment]
Sweet, much better: https://travis-ci.org/tkelman/OptimizationServices.jl/jobs/46539983 Your awesomeness continues to know no bounds.

#resolvedfixed

Now I guess I should actually write the package, huh.

**Comment by mlubin** [comment]
:+1:
