### ISSUE TITLE
Update Gtk to 3.14

### ISSUE THREAD

**Issue by tknopp** [staticfloat/homebrew-juliadeps#32]
Hi, 

It would be great if we could bump the Gtk version to 3.14. If I understand it correctly, 3.14 comes with the adwaita theme engine by default so that Gtk apps than would not look horrible anymore. I once tested this with MacPorts and manually installing the theme. Would be cool if this could become the default experience.

Thanks,

Tobi

**Comment by staticfloat** [comment]
I've just bumped a large selection of bottles, including `Gtk` to 3.14.  Let me know if this gets you the themes you want.  (For reference, Gtk windows don't look terrible on my Mac, but perhaps I'm not testing the UI controls you are interested in).  If it doesn't look right, perhaps we need to [include the `gsettings-desktop-schemas` formula by default](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gtk%2B3.rb#L28) as well?

**Comment by tknopp** [comment]
Thanks. I did try it out with

    Homebrew.update()
    Pkg.build("Gtk")

but now the Xserver does start and Gtk crashes when I use it in Julia.

**Comment by tknopp** [comment]
in the commit log I see that `"--disable-x11-backend"` was removed...

**Comment by tknopp** [comment]
I have found the formula in the Homebrew package folder, patched it with the disabled x11 backend but now I do not know how to build the formula.

**Comment by staticfloat** [comment]
D'oh!  My bad, sorry about that.  I've built a new bottle, go ahead and `Pkg.update()`, which should download the latest `gtk+3` formula.  If that doesn't work, explicitly doing `Homebrew.rm("gtk+3")` followed by `Homebrew.add("gtk+3")` should work.

**Comment by tknopp** [comment]
Thanks, I get further. 

First I see:

```
julia> Homebrew.add("gtk+3")
==> Installing gtk+3 from staticfloat/homebrew-juliadeps
==> Downloading https://juliabottles.s3.amazonaws.com/gtk+3-3.14.6_1.yosemite.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "gtk+3"
Download failed: https://juliabottles.s3.amazonaws.com/gtk+3-3
Warning: Bottle installation failed: building from source.
```

Then there was some error that python was not installed

```
==> ./configure --prefix=/Users/knopp/.julia/v0.3/Homebrew/deps/usr/Cellar/gtk+3/3.14.6_1 --disable-glibtest --enable-int
==> make install
/bin/sh: /Users/knopp/.julia/v0.3/Homebrew/deps/usr/Cellar/gobject-introspection/1.42.0/bin/g-ir-scanner: /Users/knopp/.julia/v0.3/Homebrew/deps/usr/opt/python/bin/python: bad interpreter: No such file or directory
make[3]: *** [Gdk-3.0.gir] Error 126
make[2]: *** [install-recursive] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/staticfloat/homebrew-juliadeps/issues

These open issues may also help:
gtk+3 fails to build on 10.7.5 (https://github.com/Homebrew/homebrew/issues/34191)
```

I fixed this by `Homebrew.add("python")

Now I get Gtk running and it looks a lot nicer. The icons are missing in the file chooser. And further in one app that I wrote a get a segfault. Have to investigate this.

**Comment by staticfloat** [comment]
Okay, I didn't change the `+` on the AWS server to a space, that's fixed now so you shouldn't get the 404 error anymore.  Additionally, you shouldn't have to build GTK anymore; that's really not the plan here; it should download binaries automatically so this should install without a compiler.  Can you try removing all your Homebrew GTK+ dependencies and reinstalling?

**Comment by tknopp** [comment]
Homebrew.rm("gtk+3")
Homebrew.add("gtk+3")?

Or should I rm more?

**Comment by staticfloat** [comment]
Let's start with that and see how things go.

**Comment by tknopp** [comment]
Seems to work.

My app reports: 

```
(<unknown>:24813): Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Icon 'image-missing' not present in theme
```

So there might be missing icons.

I further have several
```
(<unknown>:24813): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(<unknown>:24813): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

but this might also be me doing something wrong...

**Comment by staticfloat** [comment]
That looks like it might be you doing something wrong.  I test to make sure everything works by `include()`'ing the `tests/tests.jl` file in `Gtk.jl`.  I'm not sure where the icon files would be, if there's an environment variable we need to set to give it a certain search path, we can do that.

**Comment by tknopp** [comment]
Yes thanks. The thing with the icons is not super crucial at the moment for me but we might want to put somewhere a bug report for it?

**Comment by staticfloat** [comment]
Do you know what filenames its looking for?  Or even what directories it would be looking inside of?

**Comment by tknopp** [comment]
not really. I just report the warnings that get written to the console.

The first error is by the way

```
(<unknown>:25336): Gtk-WARNING **: Could not find the icon 'pan-down-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases
```

**Comment by staticfloat** [comment]
@tknopp is this still an issue?

**Comment by staticfloat** [comment]
I am glad to report that this has now been solved!
