### ISSUE TITLE
Heading off conflicts with system Homebrew

### ISSUE THREAD

**Issue by rsrock** [staticfloat/homebrew-juliadeps#38]
I ran into an issue again today with `Images.jl` and `imagemagick` in my systemwide Homebrew.  The way `Images` is currently set up, it assumes we're using your bottles, but the `build.jl` script will pick up the one under `/usr/local/...`

Is there a way we could add a test for a systemwide `imagemagick` (etc.), so that I'll be warned that I should `brew unlink imagemagick`?  I'd be happy to add the test, I just need to know where the best place for this would be.

**Comment by staticfloat** [comment]
Hello there!  Can you give me a sequence of operations that causes `Images` to break in the way you're describing?  In particular, I'd like to try and make `Images` "just work" as much as possible, and so if we can figure out why the systemwide `imagemagick` is causing problems, perhaps we can make ourselves immune to those problems instead.

**Comment by rsrock** [comment]
Hey @staticfloat 
Sure thing, working on it now.  Some info is at the above discussion on `Images`.

Working config, after a (system) `brew unlink imagemagick`, followed by a julia `Pkg.build("Images")` :

```
# Load dependencies
@checked_lib libwand "/Users/rrock/.julia/v0.3/Homebrew/deps/usr/lib/libMagickWand-6.Q16.dylib"

# Load-hooks
function __init__()
ENV["MAGICK_CONFIGURE_PATH"] = joinpath("/Users/rrock/.julia/v0.3/Homebrew/deps/usr/Cellar/imagemagick/6.8.9-1_1","lib","ImageMagick","config-Q16")
ENV["MAGICK_CODER_MODULE_PATH"] = joinpath("/Users/rrock/.julia/v0.3/Homebrew/deps/usr/Cellar/imagemagick/6.8.9-1_1", "lib","ImageMagick","modules-Q16","coders")
ENV["PATH"] *= ":" * joinpath("/Users/rrock/.julia/v0.3/Homebrew/deps/usr/Cellar/imagemagick/6.8.9-1_1", "bin")
end
```

Failing config, with `Pkg.build("Images")` with the symlinks for ImageMagick in the system homebrew in place (`brew link imagemagick`):

```
# Load dependencies
@checked_lib libwand "/usr/local/lib/libMagickWand-6.Q16.dylib"

# Load-hooks
function __init__()
ENV["MAGICK_CONFIGURE_PATH"] = joinpath("/Users/rrock/.julia/v0.3/Homebrew/deps/usr/Cellar/imagemagick/6.8.9-1_1","lib","ImageMagick","config-Q16")
ENV["MAGICK_CODER_MODULE_PATH"] = joinpath("/Users/rrock/.julia/v0.3/Homebrew/deps/usr/Cellar/imagemagick/6.8.9-1_1", "lib","ImageMagick","modules-Q16","coders")
ENV["PATH"] *= ":" * joinpath("/Users/rrock/.julia/v0.3/Homebrew/deps/usr/Cellar/imagemagick/6.8.9-1_1", "bin")
end
```

Notice that libwand changed, but the env variables are hardcoded to the julia homebrew.
Here, failure == the following in an IJulia session:

```
im = convert(Image, rand(5,5))
println(stringmime("image/png", im))
im

while loading In[5], in expression starting on line 2

 in error at error.jl:21
 in error at /Users/rrock/.julia/v0.3/Images/src/ioformats/libmagickwand.jl:149
 in setimageformat at /Users/rrock/.julia/v0.3/Images/src/ioformats/libmagickwand.jl:330
 in getblob at /Users/rrock/.julia/v0.3/Images/src/ioformats/libmagickwand.jl:211
 in writemime at /Users/rrock/.julia/v0.3/Images/src/io.jl:205
 in base64 at base64.jl:125
 in stringmime at multimedia.jl:82
 in stringmime at multimedia.jl:88
```

This looks to be the same as the error @one-more-minute is seeing over at timholy/Images.jl#237

**Comment by staticfloat** [comment]
This is bad.  The hooks should be getting cleared out.  I'll look into what on earth is going on inside of BinDeps here.

**Comment by rsrock** [comment]
I just checked again, and indeed the load-hooks are not being cleared when I have the system ImageMagick linked up.

**Comment by staticfloat** [comment]
@rsrock I believe I have found the error.  Could you checkout `sf/therecanbeonlyone` in `BinDeps`, restart Julia, `Pkg.build("Images")` and let me know if it fixes things for you?

**Comment by rsrock** [comment]
Well, something seems to happen.  I no longer need to `brew unlink` to get the "working config" in my second message.  So that's good.

However, I can't seem to force `Pkg.build("Images")` to pick up the system brewed ImageMagick, which would also be nice to have from time to time.  I've tried `MAGICK_HOME=/usr/local/opt/imagemagick julia` followed by `Pkg.build("Images")`, but it still picks up the Julia brewed version

**Comment by staticfloat** [comment]
Try running `Homebrew.rm("imagemagick")`.
-E

**Comment by rsrock** [comment]
Bingo!  That does it.  The load-hooks section is empty when I use the system brewed ImageMagick too.  

Thanks!

**Comment by JobJob** [comment]
Nice, this works for me, defaults to the Homebrew imagemagick and picks up my Macports ImageMagick after Homebrew.rm("imagemagick") - cheers @staticfloat !
