### ISSUE TITLE
Error: Operation already in progress for pkg-config

### ISSUE THREAD

**Issue by tdsmith** [staticfloat/homebrew-juliadeps#46]
There was a report in #machomebrew that `Pkg.add("Cairo")` fails after installing cairo's dependencies with:
```
Error: Operation already in progress for pkg-config
Another active Homebrew process is already using pkg-config.
Please wait for it to finish or terminate it to continue.
```

Homebrew is attempting to lock both `pkg-config` and `staticfloat/juliadeps/pkg-config`, which step on each other. Installing `staticfloat/juliadeps/pkg-config` first does not resolve the issue.

**Comment by tdsmith** [comment]
The failure disappears if you change `@lock = FormulaLock.new(name)` to `@lock = FormulaLock.new(full_name.gsub("/", "_"))` in formula.rb -- although this is a bad solution, since both formulas will want to write to `HOMEBREW_CELLAR/pkg-config`.

**Comment by staticfloat** [comment]
Thanks for the report @tdsmith, I have managed to solve this an alternative way, by [bringing in many of the formulae](https://github.com/staticfloat/homebrew-juliadeps/commit/fe8da41e3fe9882d296927f111a9dac77a71e8f8) from mainline Homebrew into this repository, and having them depend explicitly on `staticfloat/juliadeps/pkg-config`.
