### ISSUE TITLE
Bump SCS to v1.1.5?

### ISSUE THREAD

**Issue by joehuchette** [staticfloat/homebrew-juliadeps#50]
Could SCS be bumped to [v1.1.5](https://github.com/cvxgrp/scs/releases/tag/v1.1.5)? I'd open a PR for this, but I think builds need to manually be [put up on Amazon](https://github.com/staticfloat/homebrew-juliadeps/blob/db0717414e6ca1021de80fb456540a5d484ece44/scs.rb#L10-L16). CC @staticfloat

**Comment by tkelman** [comment]
closed by #51 #52, yeah?

**Comment by staticfloat** [comment]
Closed by 5f500660df5d88d5cffc745ee29c523f06ec5854
