### ISSUE TITLE
Bump ECOS to 2.0.2

### ISSUE THREAD

**Issue by mlubin** [staticfloat/homebrew-juliadeps#60]
Could we bump the ECOS bottle to version 2.0.2? The new tar file is at https://github.com/embotech/ecos/archive/v2.0.2.tar.gz. Hopefully shouldn't need any changes to the build script. Thanks!
CC @tkelman

**Comment by staticfloat** [comment]
I love packages that compile in less than a minute.  :)

**Comment by tkelman** [comment]
ecos is pretty small indeed. There's technically a new separate test executable for the branch and bound features but we're not using those just yet. Will find out via some future ECOS.jl PR if anything is wrong with it.

**Comment by mlubin** [comment]
Thanks @staticfloat!
