### ISSUE TITLE
Homebrew packages for MPICH and OpenMPI?

### ISSUE THREAD

**Issue by eschnett** [staticfloat/homebrew-juliadeps#74]
@staticfloat For the Julia MPI wrapper https://github.com/JuliaParallel/MPI.jl, I need to install MPICH and OpenMPI when running under OS X in Travis. Currently, I'm downloading and building from source, but this takes a long time (ten minutes each). I tried Macports, but this started by building a compiler (!) before building OpenMPI, which was even slower. I wonder whether Homebrew could provide binaries instead, or whether you can think of another solution to get OS X binaries?

**Comment by staticfloat** [comment]
The question is whether the binaries are easily relocatable.  I'm installing `OpenMPI` just to see how many hardcoded paths it has lying around, but with a piece of software this big, and targeted toward compilation, I'm not hopeful at all.  Also, Homebrew doesn't like to install `OpenMPI` and `MPICH` at the same time because they clobber eachother, (both install `mpi___` wrapper scripts) so that could be a problem as well.

**Comment by eschnett** [comment]
We won't need both packages at the same time; the user (or Travis) will choose, and install exactly one of them.

**Comment by tkelman** [comment]
If you just want to run these on travis then relocatability isn't too big a deal since they can be installed manually in .travis.yml from the mainline homebrew bottle.

**Comment by eschnett** [comment]
I am not too familiar with Homebrew. Will this build the packages, or provide binaries?

**Comment by tkelman** [comment]
Should provide binaries if upstream has made a "bottle" for the package and its dependencies - which it looks like they have for openmpi https://github.com/Homebrew/homebrew/blob/f5a3d3e3a5d21124e5e12fa4797af16b188a40e5/Library/Formula/open-mpi.rb#L7-L12 and mpich https://github.com/Homebrew/homebrew/blob/f5a3d3e3a5d21124e5e12fa4797af16b188a40e5/Library/Formula/mpich.rb#L9-L13

**Comment by eschnett** [comment]
Thanks!

**Comment by staticfloat** [comment]
Ah, yes, if Travis testing is all you're after, then `brew install $MPI_RUNTIME` (you can set environment variables in your `.travis.yml` to create a build matrix spawning multiple jobs per environment variable value, see [this page](http://docs.travis-ci.com/user/environment-variables/#Global-Variables) for details)

**Comment by eschnett** [comment]
@staticfloat Yes, the build matrix is already there.

Unfortunately, Homebrew still builds the MPI packages from scratch. Well, at least the Travis script is now simpler...

**Comment by staticfloat** [comment]
Put a `brew update` before the `brew install`.  It looks like the version of Homebrew that is bundled on the Travis bots is so old that it doesn't know about the bottles.  :)

**Comment by staticfloat** [comment]
https://travis-ci.org/staticfloat/MPI.jl/jobs/82085877

**Comment by eschnett** [comment]
Works like a charm. Thanks!
