### ISSUE TITLE
Ipopt on El Capitan

### ISSUE THREAD

**Issue by goedman** [staticfloat/homebrew-juliadeps#79]
Is this possibly be a similar El Capitan-bottle issue as with Cairo? It seems the build is trying to use GCC-4.2 (gfortran is in GCC-5.2 on my system):

2015-10-06 13:53:08 -0700

cd ThirdParty/Blas; ./configure --prefix=/Users/rob/.julia/v0.4/Homebrew/deps/usr/Cellar/ipopt/3.12.1_2 --disable-shared --with-pic; make install

checking for svnversion... yes
checking build system type... i386-apple-darwin15.0.0
checking whether we want to compile in debug mode... no
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ANSI C... none needed
configure: C compiler options are: -O3 -pipe -DNDEBUG -Wimplicit -Wparentheses -Wsequence-point -Wreturn-type -Wcast-qual -Wall -Wno-unknown-pragmas -Wno-long-long   -DBLAS_BUILD
configure: Trying to determine Fortran compiler name
checking for xlf_r... no
checking for fort77... no
checking for gfortran... no
checking for ifort... no
checking for g95... no
checking for f77... no
checking for g77... no
checking for pgf90... no
checking for pgf77... no
checking for ifc... no
checking for frt... no
checking for af77... no
configure: WARNING: Failed to find a Fortran compiler!
configure: Fortran compiler options are:  
checking how to get verbose linking output from unavailable... configure: WARNING: compilation failed

checking for Fortran libraries of unavailable... 
checking for dummy main to link with Fortran libraries... none
checking for Fortran name-mangling scheme... configure: error: cannot compile a simple Fortran program
See `config.log' for more details.
make: *** No rule to make target `install'.  Stop.

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: e6f1500728e48f4be59bb4ca2b476198f6559840
Last commit: 62 minutes ago
HOMEBREW_PREFIX: /Users/rob/.julia/v0.4/Homebrew/deps/usr
HOMEBREW_REPOSITORY: /Users/rob/.julia/v0.4/Homebrew/deps/usr
HOMEBREW_CELLAR: /Users/rob/.julia/v0.4/Homebrew/deps/usr/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 10.11.1-x86_64
Xcode: 7.1 => /Applications/Xcode-beta.app/Contents/Developer
CLT: 7.1.0.0.1.1442899023
GCC-4.2: build 0
Clang: 7.0 build 700
X11: 2.7.8_rc1 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /Users/rob/.julia/v0.4/Homebrew/deps/usr
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/Users/rob/.julia/v0.4/Homebrew/deps/usr/Library/ENV/pkgconfig/10.11
ACLOCAL_PATH: /Users/rob/.julia/v0.4/Homebrew/deps/usr/share/aclocal
PATH: /Users/rob/.julia/v0.4/Homebrew/deps/usr/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by goedman** [comment]
On my second (production) machine, the existing Ipopt, installed while still on Yosemite, continues to function after I upgraded to El Capitan.

**Comment by tseaward** [comment]
I have the same issue, even though g77 is on my path:

```
julia> Pkg.build("Ipopt")
INFO: Building Homebrew
HEAD is now at ff0d011 test: allow writing to certain var directories
HEAD is now at ce3d0c3 Merge pull request #78 from staticfloat/staging
INFO: Building Ipopt
==> Installing ipopt from staticfloat/homebrew-juliadeps
==> Downloading http://www.coin-or.org/download/source/Ipopt/Ipopt-3.12.1.tgz
Already downloaded: /Users/terryseaward/Library/Caches/Homebrew.jl/ipopt-3.12.1.tgz
==> cd ThirdParty/Blas; ./get.Blas
==> cd ThirdParty/Blas; ./configure --prefix=/Users/terryseaward/.julia/v0.4/Hom
Last 15 lines from /Users/terryseaward/Library/Logs/Homebrew/ipopt/02.3.12.1_2:
checking for g77... no
checking for pgf90... no
checking for pgf77... no
checking for ifc... no
checking for frt... no
checking for af77... no
configure: WARNING: Failed to find a Fortran compiler!
configure: Fortran compiler options are:  
checking how to get verbose linking output from unavailable... configure: WARNING: compilation failed

checking for Fortran libraries of unavailable... 
checking for dummy main to link with Fortran libraries... none
checking for Fortran name-mangling scheme... configure: error: cannot compile a simple Fortran program
See `config.log' for more details.
make: *** No rule to make target `install'.  Stop.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/staticfloat/homebrew-juliadeps/issues

Warning: 
================================[ ERROR: Ipopt ]================================

LoadError: failed process: Process(`/Users/terryseaward/.julia/v0.4/Homebrew/deps/usr/bin/brew install --force-bottle staticfloat/juliadeps/ipopt`, ProcessExited(1)) [1]
while loading /Users/terryseaward/.julia/v0.4/Ipopt/deps/build.jl, in expression starting on line 73

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Ipopt had build errors.

 - packages with build errors remain installed in /Users/terryseaward/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Ipopt")`
 - build a single package by running its `deps/build.jl` script

================================================================================
```
```
shell> g77
g77: no input files

```

**Comment by goedman** [comment]
@tseaward,

Hi Terry, I did 2 things. Below is what I think fixed it: simply exporting the proper fortran compiler using the environment variable FC (I did that by typing ```;export FC=gfortran``` in the REPL and restarting Julia.

The other thing I did (first in fact) is brew-ing ipopt outside of Julia:
```
brew update
brew install homebrew/science/ipopt
```

That certainly worked but didn't fix the Julia issue.

Regards,
Rob

------------------------------------------------------------------------------------------------------

julia> using Ipopt
ERROR: LoadError: Ipopt not properly installed. Please run Pkg.build("Ipopt")
 in error at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/rob/.julia/v0.4/Ipopt/src/Ipopt.jl, in expression starting on line 6

shell> export FC=gfortran

julia> Pkg.build("Ipopt")
INFO: Building Homebrew
remote: Counting objects: 45, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 45 (delta 35), reused 38 (delta 28), pack-reused 0
Unpacking objects: 100% (45/45), done.
From https://github.com/Homebrew/homebrew
   f1a93e5..715e055  master     -> origin/master
HEAD is now at 715e055 postgresql: update 9.4.5 bottle.
HEAD is now at ce3d0c3 Merge pull request #78 from staticfloat/staging
INFO: Building Ipopt

julia> 
Robs-15inch:~ rob$ clear; julia4

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0 (2015-10-08 06:20 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> include("/Users/rob/.julia/v0.4/Ipopt/test/runtests.jl")
INFO: Recompiling stale cache file /Users/rob/.julia/lib/v0.4/MathProgBase.ji for module MathProgBase.

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.12.1, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        4
Number of nonzeros in inequality constraint Jacobian.:        4
Number of nonzeros in Lagrangian Hessian.............:       10

Total number of variables............................:        4
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        4
                     variables with only upper bounds:        0
Total number of equality constraints.................:        1
Total number of inequality constraints...............:        1
        inequality constraints with only lower bounds:        1
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  1.6109693e+01 1.12e+01 5.28e-01  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  1.6982239e+01 7.30e-01 1.02e+01  -1.0 6.11e-01    -  7.19e-02 1.00e+00f  1
   2  1.7318411e+01 3.60e-02 5.05e-01  -1.0 1.61e-01    -  1.00e+00 1.00e+00h  1
   3  1.6849424e+01 2.78e-01 6.68e-02  -1.7 2.85e-01    -  7.94e-01 1.00e+00h  1
   4  1.7051199e+01 4.71e-03 2.78e-03  -1.7 6.06e-02    -  1.00e+00 1.00e+00h  1
   5  1.7011979e+01 7.19e-03 8.50e-03  -3.8 3.66e-02    -  9.45e-01 9.98e-01h  1
   6  1.7014271e+01 1.74e-05 9.78e-06  -3.8 3.33e-03    -  1.00e+00 1.00e+00h  1
   7  1.7014021e+01 1.23e-07 1.82e-07  -5.7 2.69e-04    -  1.00e+00 1.00e+00h  1
   8  1.7014017e+01 1.77e-11 2.52e-11  -8.6 3.32e-06    -  1.00e+00 1.00e+00h  1

Number of Iterations....: 8

... lots more output ... <snipped>

**Comment by tkelman** [comment]
`g77` isn't really going to work, the mumps solver is in Fortran 90. The formulas here shouldn't need to be building from source. Homebrew tries to isolate its environment to avoid picking up random things you may have lying around on your path. The Ipopt bottle (and probably quite a few others) just needs to be rebuilt for El Capitan, ref https://github.com/staticfloat/homebrew-juliadeps/blob/master/ipopt.rb - I believe there have been issues with the mac buildbots that has been slowing some of the work down.

**Comment by goedman** [comment]
Thanks Tony. I also found that after building Ipopt I needed to get rid of the FC setting for some other packages, e.g. Cairo, to update properly. 

@tseaward, can I close this issue?

**Comment by tseaward** [comment]
@goedman Yes, thank you for all your help, much appreciated.

**Comment by goedman** [comment]
@tseaward You're welcome, although it didn't really help you. But I've learned a bit about formulas, bottles and taps! (I also try to keep the Bayesian packages Jags.jl and Stan.jl up to date, hence my interest. There is a Homebrew formula for Jags, which works fine, but I'm still struggling in developing a formula for Stan. Stan's makefile is rather special.)
