### ISSUE TITLE
Invalid glib patch url

### ISSUE THREAD

**Issue by tibaes** [staticfloat/homebrew-juliadeps#86]
In the file homebrew-juliadeps/glib.rb, line 48,the url 
https://gist.githubusercontent.com/jacknagel/9835034/raw/282d36efc126272f3e73206c9865013f52d67cd8/gio.patch
results in 404 error (not found).

**Comment by staticfloat** [comment]
@tibaes I have just merged a large change to all the formulae in this repository, please `using Homebrew; Homebrew.update()` and try again.

**Comment by tibaes** [comment]
Thanks, it worked! :+1:
